### ISSUE TITLE
The scoring function [Back-end]

### ISSUE THREAD

**Issue by aiushiusi** [TSP-24/TSP-24#10]
We need a student class to store all the assessment items and come up with an algorithm to calculate the student's engagement score based on them.

Acceptance Criteria:

- [x] Generate the fake CSV data files
Using Python program to generate the fake data

- [x] Function can be fine-tuned and adapts to various CSV column heading formats.
- [x] #21

**Comment by wyfgood1999** [comment]
finished: 
- Generates synthetic student data including names, IDs, and email addresses.
- Generates random student scores based on a normal distribution with customizable mean and standard deviation.
- Utilizes course assessment data to calculate student grades.
- Outputs grades data to CSV files for further analysis or integration with other systems.
- Transform the format CSV and JSON

**Comment by xuanan20020** [comment]
A few commits regarding the scoring function were lost (due to a force merge from Ahmed a few days ago) but I have a local backup to restore the basic function [here](https://github.com/TSP-24/TSP-24/commit/def2830946f470b3a1cd4c006f1d633387a70904). A more fine-tuned [version](https://github.com/TSP-24/TSP-24/commit/b28032be3401c1eeb51743c4a5f70fd038d16f75) is pushed not long after.

**Comment by xuanan20020** [comment]
Converted the interaction with database as an issue #21 of its own.

**Comment by xuanan20020** [comment]
During the Week 9 [client meeting](https://docs.google.com/document/d/15bdL5Y37_nBO5dc_ZcUi00amXGDVDac7/edit), it was agreed in meeting minute bullet point 8 that we need to update the format of the fake data we generate to include assignment deadlines. 

The data generator will need to be updated to fulfill this new requirement, as in issue #20.

**Comment by xuanan20020** [comment]
> During the Week 9 [client meeting](https://docs.google.com/document/d/15bdL5Y37_nBO5dc_ZcUi00amXGDVDac7/edit), it was agreed in meeting minute bullet point 8 that we need to update the format of the fake data we generate to include assignment deadlines.
> 
> The data generator will need to be updated to fulfill this new requirement, as in issue #20.

Data generator is [updated](https://github.com/TSP-24/TSP-24/commit/df222dc04d6ff2a1cb68bb0ec7c9ed2a651347a7) as per new requirements.

**Comment by xuanan20020** [comment]
The feasibility and value of completing the Database Interaction were determined to be limited during the [week 10](https://docs.google.com/document/d/1x4Wy-VhQtsXWwoFCneiNtUawo0DREE_4/edit) team meeting. Due to a shortage of manpower, this task will be postponed to a future sprint. However, the exclusion of this feature should not significantly impact the value provided in the pre-MVP delivered in audit 3.

Still keeping this as one of the acceptance criteria for future references (i.e. tracing back to why the feature is needed originally).
