### ISSUE TITLE
Front-end/back-end interaction [Back-end][Front-end]

### ISSUE THREAD

**Issue by aiushiusi** [TSP-24/TSP-24#16]
We need to implement an interface that allows the back and front end to communicate seamlessly.

Acceptance criteria:

 - [x] #21 
 - [x] Implement Front-to-Back-end function calls. 
 - [x] Update instructions in README.md for [backend](https://github.com/TSP-24/TSP-24/tree/develop/backend) and [frontend](https://github.com/TSP-24/TSP-24/tree/develop/frontend).

**Comment by wyfgood1999** [comment]
The interaction between the front and back ends: 
once clicking the upload button, the CSV file of the students’ information should be saved in a local file folder. The Python script uploadandupdatedata.py should be called to do the data uploading/updating.
Subsequently, the back-end data is returned to the front-end for display.

**Comment by xuanan20020** [comment]
The front end now sends the entire file content to the back end, bypassing JavaScript's file path restrictions (which renders the previous approach unfeasible). The Flask server processes this data and returns it in JSON format to the front end for use.

The basic interaction is [complete](https://github.com/TSP-24/TSP-24/commit/226b93ea23bd519b767917b33b3a804a80f33a38) (no database involved yet).

**Comment by xuanan20020** [comment]
Instructions in README.md are [updated](https://github.com/TSP-24/TSP-24/commit/c5fd220271be5d9880bdbb9ec9d424e9a1ca033c) to simplify the process of running the server.

**Comment by xuanan20020** [comment]
The feasibility and value of completing the **Database Interaction** were determined to be limited during the [week 10](https://docs.google.com/document/d/1x4Wy-VhQtsXWwoFCneiNtUawo0DREE_4/edit) team meeting. Due to a shortage of manpower, this task will be postponed to a future sprint. However, the exclusion of this feature should not significantly impact the value provided in the pre-MVP delivered in audit 3.


Still keeping this as one of the acceptance criteria for future references (i.e. tracing back to why the feature is needed originally).
